"""Hold the hand-written fakes to a recording of the real entities.

``_amount_for`` and ``_customer_for`` were first written against a guessed
subscription entity, and the fakes encoded the same guess. They agreed with each
other and with nothing else, so a green suite said the live path worked while it
was broken. The shape was corrected against the live account and the correction
was written down in a commit message -- true when written, checkable by nobody,
which is precisely how the "reproduce with no API key" claim in D61 rotted.

``tests/fixtures/entity_shapes.json`` is that claim as an artefact: field names
and value types, no values, regenerated by
``python -m scripts.record_entity_shapes``. These tests fail if a fake invents a
field the API does not return, if it gives one the wrong type, or if production
reads a field the recording has never seen.
"""

import json
from pathlib import Path

import pytest

from tests.razorpay.test_payment_links import real_plan, real_subscription

RECORDING = json.loads(
    (Path(__file__).parent.parent / "fixtures" / "entity_shapes.json").read_text(
        encoding="utf-8"
    )
)["entities"]

#: Fields production actually reads off each entity. Every one must exist in the
#: recording, or the code is reading something the API does not send.
READ_BY_PRODUCTION = {
    "subscription": ["plan_id", "customer_email", "customer_contact", "status", "short_url"],
    "plan": ["item"],
}


def type_name(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, dict):
        return "dict"
    if isinstance(value, list):
        return "list"
    return type(value).__name__


def test_the_recording_exists_and_covers_both_entities():
    """Guards the guard: an empty recording would make everything below vacuous."""
    assert set(RECORDING) >= {"subscription", "plan"}
    assert RECORDING["subscription"] and RECORDING["plan"]


def test_the_recording_holds_no_values_only_names_and_types():
    """It is committed and the account is real. Names and types are the whole
    claim; an email address or an amount would be someone's data."""
    allowed = {"str", "int", "float", "bool", "null", "list"}

    def check(shape: dict, path: str = "") -> None:
        for key, value in shape.items():
            where = f"{path}.{key}" if path else key
            if isinstance(value, dict):
                check(value, where)
            else:
                assert value in allowed, f"{where} recorded a value, not a type: {value!r}"

    for entity, shape in RECORDING.items():
        check(shape, entity)


@pytest.mark.parametrize(
    ("entity", "fields"), sorted(READ_BY_PRODUCTION.items()), ids=lambda v: str(v)[:20]
)
def test_production_never_reads_a_field_the_api_does_not_send(entity, fields):
    recorded = RECORDING[entity]
    missing = [field for field in fields if field not in recorded]
    assert not missing, (
        f"{entity} entity: production reads {', '.join(missing)}, which the recorded live "
        "entity does not contain. This is the guessed-shape bug, again."
    )


@pytest.mark.parametrize(
    ("entity", "fake"),
    [("subscription", real_subscription()), ("plan", real_plan())],
    ids=["subscription", "plan"],
)
def test_the_fakes_invent_no_field_the_real_entity_lacks(entity, fake):
    recorded = RECORDING[entity]
    invented = [key for key in fake if key not in recorded]
    assert not invented, (
        f"the {entity} fake supplies {', '.join(invented)}, which a real entity does not "
        "have. A fake that is more generous than the API tests an assumption, not the API."
    )


@pytest.mark.parametrize(
    ("entity", "fake"),
    [("subscription", real_subscription()), ("plan", real_plan())],
    ids=["subscription", "plan"],
)
def test_the_fakes_give_every_field_the_type_the_api_gives_it(entity, fake):
    recorded = RECORDING[entity]
    for key, value in fake.items():
        expected = recorded.get(key)
        if isinstance(expected, dict):
            assert isinstance(value, dict), f"{entity}.{key} is an object on the real entity"
            continue
        if expected == "null":
            # The recorded account happened to have nothing here. A fake that
            # supplies a value is exercising the populated case on purpose.
            continue
        assert type_name(value) == expected, (
            f"{entity}.{key} is {expected} on the real entity, {type_name(value)} in the fake"
        )
